name: formation-ai
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pip
  - numpy
  - pandas
  - pytorch 
  - cpuonly
  - torchvision
  - scikit-learn
  - pip:
    - tqdm
    - Pillow
    - celluloid 
    - pydotplus
    - seaborn
    - nltk
